[build-system]
requires = ["setuptools>=42", "wheel", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sequenzo"
version = "0.1.0"
description = "A fast, scalable and intuitive Python package for social sequence analysis."
readme = "README.md"
authors = [{ name = "Yuqi Liang", email = "yuqi.liang.1900@gmail.com" },
           { name = "Xinyi Li", email = "1836724126@qq.com"},
           { name = "Jan Heinrich Ernst Meyerhoff-Liang", email = "jan.meyerhoff1@gmail.com"}]
license = { file = "LICENSE" }
# TODO: How do I know all the dependencies I need?
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "Pillow",
    "pybind11>=2.6.0",
    "scipy"
]

[project.urls]
Homepage = "https://github.com/Liang-Team/Sequenzo"
# TODO: change
Documentation = "https://sequenzo.yuqi-liang.tech"

[tool.setuptools]
packages = ["sequenzo"]
package-dir = {"" = "."}

[tool.setuptools.package-data]
"sequenzo.datasets" = ["country_CO2_emissions.csv", "country_income.csv"]

[[tool.setuptools.ext-modules]]
name = "sequenzo.dissimilarity_measures.c_code"
sources = [
    "sequenzo/dissimilarity_measures/src/module.cpp"
]
include-dirs = ["${PYBIND11_INCLUDE_DIR}", "${PYTHON_INCLUDE_DIR}"]
extra-compile-args = ["-std=c++11"]