[build-system]
requires = ["setuptools>=42", "wheel", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sequenzo"
version = "0.1.0"
description = "A fast, scalable and intuitive Python package for social sequence analysis."
readme = "README.md"
authors = [
    { name = "Yuqi Liang", email = "yuqi.liang.1900@gmail.com" },
    { name = "Xinyi Li", email = "1836724126@qq.com"},
    { name = "Jan Heinrich Ernst Meyerhoff-Liang", email = "jan.meyerhoff1@gmail.com"}
]
license = { file = "LICENSE" }

dependencies = [
    "numpy<2.0",
    "pandas",
    "matplotlib",
    "seaborn",
    "Pillow",
    "pybind11>=2.6.0",
    "scipy",
    "scikit-learn",
    "fastcluster",
    "joblib",
]

[project.optional-dependencies]
dev = ["pytest", "flake8"]

[project.urls]
Homepage = "https://github.com/Liang-Team/Sequenzo"
Documentation = "https://sequenzo.yuqi-liang.tech"

[tool.setuptools]
python-requires = ">=3.8,<3.11"
packages = ["sequenzo"]
package-dir = {"" = "."}

[tool.setuptools.package-data]
"sequenzo.datasets" = ["country_CO2_emissions.csv", "country_income.csv"]

# 对于动态配置，如果需要，可以这样添加
[tool.setuptools.dynamic]
version = {attr = "sequenzo.__version__"}