"""
@Author  : Xinyi Li 李欣怡
@File    : test_fuzzy_clustering_weightedcluster.py
@Desc    :
Tests for fuzzy clustering modules vs WeightedCluster / cluster::fanny R references.

Covers:
  - dyadic_children subset (first NROWS sequences): FANNY, wfcmdd variants.
  - crispness, membership_summary, most_typical_members.

Three main groups (with WeightedCluster ref comparison):
  1) FANNY: default memb_exp=1.5 / memb_exp=2.0, k=2..4 (membership matrix,
     clustering assignment, objective).
  2) wfcmdd variants: FCMdd, NCdd, HNCdd, PCMdd (membership shape, functional,
     medoid indices).
  3) Helper functions: crispness (norm / unnorm), membership_summary statistics,
     most_typical_members per cluster.

Additional "parameter config" tests (Parts 1b, 2b): same algorithms with different
parameter values (memb_exp, m, dnoise, alpha). These also compare against WeightedCluster;
refs are generated by weightedcluster_fuzzy_reference.R.

Usage:
    pytest test_fuzzy_clustering_weightedcluster.py -v
"""

import os
import subprocess
import tempfile

import numpy as np
import pandas as pd
import pytest

from sequenzo import SequenceData
from sequenzo.datasets import load_dataset

# ---------------------------------------------------------------------------
# Import the Sequenzo fuzzy clustering modules under test
# ---------------------------------------------------------------------------
from sequenzo.clustering.fuzzy_clustering import (
    FuzzyClusterResult,
    WfcmddResult,
    crispness,
    get_fuzzy_clusters,
    membership_summary,
    most_typical_members,
    wfcmdd,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
NROWS = 20  # must match the R script default (dyadic_children)
N_CLUSTERS = 3  # default k for most tests
# PCMdd R reference: WeightedCluster PCMdd fails on dyadic_children; use mvad + committed CSV.
PCMDD_NROWS = 30
PCMDD_REF_MEMB = "wfcmdd_pcmdd_k3_memb"
THIS_DIR = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Helpers shared with the R fixture
# ---------------------------------------------------------------------------

def _dyadic_children_subset(nrows=NROWS):
    """Load dyadic_children and return first nrows rows as DataFrame."""
    df = load_dataset("dyadic_children")
    time_list = [c for c in df.columns if str(c).isdigit()]
    time_list = sorted(time_list, key=int)
    df = df.head(nrows)
    return df, time_list


def _sequence_data_from_df(df, time_list):
    """Build SequenceData like lcp-lsog notebook: states 1..6, id_col dyadID."""
    states = [1, 2, 3, 4, 5, 6]
    return SequenceData(
        df,
        time=time_list,
        id_col="dyadID",
        states=states,
    )


def _run_r_reference(csv_path, nrows, outdir, script_name, timeout=120, required_refs=()):
    """Run R script to generate ref_*.csv in outdir. Returns True if success."""
    r_script = os.path.join(THIS_DIR, script_name)
    if not os.path.isfile(r_script):
        return False
    try:
        result = subprocess.run(
            ["Rscript", r_script, csv_path, str(nrows), outdir],
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=THIS_DIR,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False
    if result.returncode == 0:
        return True
    if required_refs and all(
        os.path.isfile(os.path.join(outdir, f"ref_{name}.csv")) for name in required_refs
    ):
        return True
    return False


def _load_ref_csv(outdir, name):
    """Load reference CSV. Returns DataFrame or None if not found."""
    path = os.path.join(outdir, f"ref_{name}.csv")
    if not os.path.isfile(path):
        return None
    return pd.read_csv(path, index_col=0)


def _load_ref_value(outdir, name):
    """Load a single reference scalar from ref_<name>.csv (first cell)."""
    path = os.path.join(outdir, f"ref_{name}.csv")
    if not os.path.isfile(path):
        return None
    df = pd.read_csv(path)
    if df.empty or df.shape[1] < 1:
        return None
    return float(df.iloc[0, 0])


def _build_distance_matrix(seqdata):
    """Return a condensed square distance matrix (OM, TRATE, maxlength)."""
    from sequenzo.dissimilarity_measures import get_distance_matrix
    D = get_distance_matrix(seqdata, method="OM", sm="TRATE", indel="auto", norm="maxlength")
    return np.asarray(D, dtype=np.float64)


def _mvad_subset(nrows=PCMDD_NROWS):
    """First nrows of mvad (TraMineR clustassoc / seqhmm convention: cols 17–86)."""
    df = load_dataset("mvad").head(nrows)
    time_list = list(df.columns[16:86])
    return df, time_list


def _sequence_data_mvad(df, time_list):
    alphabet = ["employment", "FE", "HE", "joblessness", "school", "training"]
    labels = [
        "employment",
        "further education",
        "higher education",
        "joblessness",
        "school",
        "training",
    ]
    return SequenceData(
        df,
        time=time_list,
        id_col="id",
        states=alphabet,
        labels=labels,
    )


def _build_distance_matrix_pcmdd(seqdata):
    """HAM distance on mvad (stable PCMdd reference; see ref_wfcmdd_pcmdd_k3_memb.csv)."""
    from sequenzo.dissimilarity_measures import get_distance_matrix
    D = get_distance_matrix(seqdata, method="HAM", norm="auto")
    return np.asarray(D, dtype=np.float64)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def seqdata_and_diss():
    """SequenceData + precomputed distance matrix for the first NROWS sequences."""
    df, time_list = _dyadic_children_subset(NROWS)
    sd = _sequence_data_from_df(df, time_list)
    D = _build_distance_matrix(sd)
    return sd, D


@pytest.fixture(scope="module")
def ref_dir_fanny(seqdata_and_diss):
    """Generate WeightedCluster / cluster::fanny reference CSVs, or use THIS_DIR."""
    sd, _ = seqdata_and_diss
    for name in ["fanny_k3_exp15_memb", "fanny_k3_exp15_obj"]:
        if os.path.isfile(os.path.join(THIS_DIR, f"ref_{name}.csv")):
            return THIS_DIR
    df, _ = _dyadic_children_subset(NROWS)
    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as f:
        df.to_csv(f.name, index=False)
        csv_path = f.name
    try:
        outdir = tempfile.mkdtemp()
        ok = _run_r_reference(
            csv_path,
            NROWS,
            outdir,
            "weightedcluster_fuzzy_reference.R",
            required_refs=("fanny_k3_exp15_memb", "fanny_k3_exp15_obj"),
        )
        if ok:
            return outdir
    finally:
        try:
            os.unlink(csv_path)
        except Exception:
            pass
    pytest.skip(
        "R reference generation failed; run: "
        "Rscript tests/clustering/weightedcluster_fuzzy_reference.R <csv> 20 tests/clustering"
    )


@pytest.fixture(scope="module")
def seqdata_pcmdd():
    """mvad subset for PCMdd vs committed membership reference (R PCMdd unavailable on dyadic)."""
    df, time_list = _mvad_subset(PCMDD_NROWS)
    sd = _sequence_data_mvad(df, time_list)
    D = _build_distance_matrix_pcmdd(sd)
    return sd, D


@pytest.fixture(scope="module")
def ref_dir_wfcmdd(seqdata_and_diss):
    """Generate wfcmdd reference CSVs."""
    for name in ["wfcmdd_fcmdd_k3_memb", "wfcmdd_fcmdd_k3_functional"]:
        if os.path.isfile(os.path.join(THIS_DIR, f"ref_{name}.csv")):
            return THIS_DIR
    df, _ = _dyadic_children_subset(NROWS)
    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as f:
        df.to_csv(f.name, index=False)
        csv_path = f.name
    try:
        outdir = tempfile.mkdtemp()
        ok = _run_r_reference(
            csv_path,
            NROWS,
            outdir,
            "weightedcluster_fuzzy_reference.R",
            required_refs=("wfcmdd_fcmdd_k3_memb", "wfcmdd_fcmdd_k3_functional"),
        )
        if ok:
            return outdir
    finally:
        try:
            os.unlink(csv_path)
        except Exception:
            pass
    pytest.skip(
        "R reference generation failed; run: "
        "Rscript tests/clustering/weightedcluster_fuzzy_reference.R <csv> 20 tests/clustering"
    )


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _assert_valid_membership(memb, n, k):
    """Assert membership matrix is (n, k), row-stochastic, non-negative, finite."""
    assert isinstance(memb, np.ndarray), "membership must be np.ndarray"
    assert memb.shape == (n, k), f"Expected ({n}, {k}), got {memb.shape}"
    assert np.all(np.isfinite(memb)), "membership contains non-finite values"
    assert np.all(memb >= -1e-9), "membership must be non-negative"
    row_sums = memb.sum(axis=1)
    np.testing.assert_allclose(row_sums, 1.0, atol=1e-6, err_msg="membership rows must sum to 1")


def _compare_membership_matrices(got, ref_df, atol=1e-4, rtol=1e-4):
    """Compare Sequenzo membership (n, k) vs R reference DataFrame."""
    ref = ref_df.to_numpy(dtype=np.float64)
    assert got.shape == ref.shape, f"Shape mismatch: Sequenzo {got.shape} vs R {ref.shape}"
    # Membership columns may be permuted; align by Hungarian matching on column correlation
    k = got.shape[1]
    col_order = _match_columns(got, ref)
    ref_aligned = ref[:, col_order]
    np.testing.assert_allclose(
        got, ref_aligned, atol=atol, rtol=rtol,
        err_msg="Membership matrix differs from WeightedCluster reference"
    )


def _match_columns(a, b):
    """Match columns of b to columns of a by minimum sum-of-squared-differences."""
    from itertools import permutations
    k = a.shape[1]
    best_perm = list(range(k))
    best_cost = np.inf
    for perm in permutations(range(k)):
        cost = np.sum((a - b[:, list(perm)]) ** 2)
        if cost < best_cost:
            best_cost = cost
            best_perm = list(perm)
    return best_perm


# =============================================================================
# Part 1: FANNY (cluster::fanny via Sequenzo wrapper)
# =============================================================================

class TestFanny:
    """Tests for get_fuzzy_clusters with method='fanny'."""

    def test_fanny_returns_fuzzy_cluster_result(self, seqdata_and_diss):
        """get_fuzzy_clusters(method='fanny') returns FuzzyClusterResult."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        assert isinstance(result, FuzzyClusterResult)

    def test_fanny_membership_shape(self, seqdata_and_diss):
        """FANNY membership matrix is (NROWS, k)."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        _assert_valid_membership(result.membership, NROWS, N_CLUSTERS)

    def test_fanny_clustering_shape(self, seqdata_and_diss):
        """FANNY hard clustering vector has length NROWS with values in [0, k-1]."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        assert result.clustering is not None
        clust = result.clustering
        assert len(clust) == NROWS
        assert set(clust).issubset(set(range(N_CLUSTERS)))

    def test_fanny_method_attribute(self, seqdata_and_diss):
        """FuzzyClusterResult.method == 'fanny'."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        assert result.method == "fanny"

    def test_fanny_memb_exp_stored(self, seqdata_and_diss):
        """FuzzyClusterResult.memb_exp matches requested value."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        assert np.isclose(result.memb_exp, 1.5)

    def test_fanny_objective_positive(self, seqdata_and_diss):
        """FANNY objective value is positive."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        assert result.objective is not None and result.objective > 0

    def test_fanny_k2(self, seqdata_and_diss):
        """FANNY with k=2 produces valid membership."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=2, memb_exp=1.5, method="fanny")
        _assert_valid_membership(result.membership, NROWS, 2)

    def test_fanny_k4(self, seqdata_and_diss):
        """FANNY with k=4 produces valid membership."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=4, memb_exp=1.5, method="fanny")
        _assert_valid_membership(result.membership, NROWS, 4)

    def test_fanny_membership_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """FANNY k=3, memb_exp=1.5 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_fanny, "fanny_k3_exp15_memb")
        if D_ref is None:
            pytest.skip("ref_fanny_k3_exp15_memb.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        _compare_membership_matrices(result.membership, D_ref, atol=1e-4)

    def test_fanny_objective_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """FANNY k=3, memb_exp=1.5 objective matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        ref_val = _load_ref_value(ref_dir_fanny, "fanny_k3_exp15_obj")
        if ref_val is None:
            pytest.skip("ref_fanny_k3_exp15_obj.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        assert np.isclose(result.objective, ref_val, rtol=1e-4, atol=1e-6), (
            f"Sequenzo objective={result.objective}, WeightedCluster={ref_val}"
        )


# ----- Part 1b: FANNY parameter configs -----

class TestFannyParameterConfigs:
    """FANNY with non-default memb_exp vs WeightedCluster."""

    def test_fanny_memb_exp_20_membership_shape(self, seqdata_and_diss):
        """FANNY memb_exp=2.0, k=3 produces (NROWS, 3) membership."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=2.0, method="fanny")
        _assert_valid_membership(result.membership, NROWS, N_CLUSTERS)

    def test_fanny_memb_exp_20_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """FANNY memb_exp=2.0, k=3 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_fanny, "fanny_k3_exp20_memb")
        if D_ref is None:
            pytest.skip("ref_fanny_k3_exp20_memb.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=2.0, method="fanny")
        _compare_membership_matrices(result.membership, D_ref, atol=1e-4)

    def test_fanny_k2_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """FANNY k=2, memb_exp=1.5 membership matches WeightedCluster."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_fanny, "fanny_k2_exp15_memb")
        if D_ref is None:
            pytest.skip("ref_fanny_k2_exp15_memb.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=2, memb_exp=1.5, method="fanny")
        _compare_membership_matrices(result.membership, D_ref, atol=1e-4)

    def test_fanny_k4_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """FANNY k=4, memb_exp=1.5 membership matches WeightedCluster."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_fanny, "fanny_k4_exp15_memb")
        if D_ref is None:
            pytest.skip("ref_fanny_k4_exp15_memb.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=4, memb_exp=1.5, method="fanny")
        _compare_membership_matrices(result.membership, D_ref, atol=1e-4)


# =============================================================================
# Part 2: wfcmdd variants (FCMdd, NCdd, HNCdd, PCMdd)
# =============================================================================

class TestWfcmdd:
    """Tests for wfcmdd and get_fuzzy_clusters(method='wfcmdd')."""

    # ----- FCMdd -----

    def test_fcmdd_returns_wfcmdd_result(self, seqdata_and_diss):
        """wfcmdd(method='FCMdd') returns WfcmddResult."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        assert isinstance(result, WfcmddResult)

    def test_fcmdd_membership_shape(self, seqdata_and_diss):
        """FCMdd membership is (NROWS, k) and row-stochastic."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        _assert_valid_membership(result.memb[:, :N_CLUSTERS], NROWS, N_CLUSTERS)

    def test_fcmdd_mobile_centers(self, seqdata_and_diss):
        """FCMdd mobile_centers are valid row indices into the distance matrix."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        assert result.mobile_centers.shape == (N_CLUSTERS,)
        assert np.all(result.mobile_centers >= 0)
        assert np.all(result.mobile_centers < NROWS)

    def test_fcmdd_functional_positive(self, seqdata_and_diss):
        """FCMdd functional is positive."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        assert result.functional > 0

    def test_fcmdd_method_attribute(self, seqdata_and_diss):
        """WfcmddResult.method == 'FCMdd'."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        assert result.method == "FCMdd"

    def test_fcmdd_membership_matches_weightedcluster(self, seqdata_and_diss, ref_dir_wfcmdd):
        """FCMdd k=3, m=2.0 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_wfcmdd, "wfcmdd_fcmdd_k3_memb")
        if D_ref is None:
            pytest.skip("ref_wfcmdd_fcmdd_k3_memb.csv not found")
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        _compare_membership_matrices(result.memb[:, :N_CLUSTERS], D_ref, atol=1e-4)

    def test_fcmdd_functional_matches_weightedcluster(self, seqdata_and_diss, ref_dir_wfcmdd):
        """FCMdd k=3, m=2.0 functional matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        ref_val = _load_ref_value(ref_dir_wfcmdd, "wfcmdd_fcmdd_k3_functional")
        if ref_val is None:
            pytest.skip("ref_wfcmdd_fcmdd_k3_functional.csv not found")
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=2.0)
        assert np.isclose(result.functional, ref_val, rtol=1e-3, atol=1e-5), (
            f"Sequenzo functional={result.functional}, WeightedCluster={ref_val}"
        )

    # ----- NCdd -----

    def test_ncdd_membership_shape(self, seqdata_and_diss):
        """NCdd membership is (NROWS, k+1) with noise column."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        dnoise = float(np.median(D[D > 0]))
        result = wfcmdd(D, memb=seeds, method="NCdd", m=2.0, dnoise=dnoise)
        assert result.memb.shape[0] == NROWS
        assert result.memb.shape[1] == N_CLUSTERS + 1  # +1 for noise cluster

    def test_ncdd_membership_matches_weightedcluster(self, seqdata_and_diss, ref_dir_wfcmdd):
        """NCdd k=3 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_wfcmdd, "wfcmdd_ncdd_k3_memb")
        if D_ref is None:
            pytest.skip("ref_wfcmdd_ncdd_k3_memb.csv not found")
        seeds = np.array([0, 5, 10])
        dnoise = float(np.median(D[D > 0]))
        result = wfcmdd(D, memb=seeds, method="NCdd", m=2.0, dnoise=dnoise)
        _compare_membership_matrices(result.memb, D_ref, atol=1e-4)

    # ----- HNCdd -----

    def test_hncdd_membership_is_crisp(self, seqdata_and_diss):
        """HNCdd produces hard (crisp) assignments: each row has exactly one 1."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        dnoise = float(np.median(D[D > 0]))
        result = wfcmdd(D, memb=seeds, method="HNCdd", dnoise=dnoise)
        # rows for mobile clusters: each row of the mobility part should be 0 or 1
        mobile_memb = result.memb[:, :N_CLUSTERS]
        assert np.all((mobile_memb == 0) | np.isclose(mobile_memb, 1.0, atol=1e-9)), (
            "HNCdd membership should be crisp (0 or 1)"
        )

    def test_hncdd_membership_matches_weightedcluster(self, seqdata_and_diss, ref_dir_wfcmdd):
        """HNCdd k=3 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_wfcmdd, "wfcmdd_hncdd_k3_memb")
        if D_ref is None:
            pytest.skip("ref_wfcmdd_hncdd_k3_memb.csv not found")
        seeds = np.array([0, 5, 10])
        dnoise = float(np.median(D[D > 0]))
        result = wfcmdd(D, memb=seeds, method="HNCdd", dnoise=dnoise)
        _compare_membership_matrices(result.memb, D_ref, atol=1e-4)

    # ----- PCMdd -----

    def test_pcmdd_membership_shape(self, seqdata_and_diss):
        """PCMdd membership is (NROWS, k) with values in [0, 1]."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        eta = np.array([0.5, 0.5, 0.5])
        result = wfcmdd(D, memb=seeds, method="PCMdd", m=2.0, eta=eta)
        assert result.memb.shape == (NROWS, N_CLUSTERS)
        assert np.all(result.memb >= -1e-9)
        assert np.all(result.memb <= 1.0 + 1e-9)

    def test_pcmdd_membership_matches_weightedcluster(self, seqdata_pcmdd):
        """PCMdd k=3 membership matches committed mvad reference (HAM, seeds 0/5/10).

        WeightedCluster 1.8.x PCMdd fails on dyadic_children; ref is stored under
        tests/clustering/ref_wfcmdd_pcmdd_k3_memb.csv (regenerate with mvad + wfcmdd).
        """
        _, D = seqdata_pcmdd
        ref_path = os.path.join(THIS_DIR, f"ref_{PCMDD_REF_MEMB}.csv")
        if not os.path.isfile(ref_path):
            pytest.skip(f"ref_{PCMDD_REF_MEMB}.csv not found in {THIS_DIR}")
        D_ref = pd.read_csv(ref_path, index_col=0)
        seeds = np.array([0, 5, 10])
        eta = np.array([0.5, 0.5, 0.5])
        result = wfcmdd(D, memb=seeds, method="PCMdd", m=2.0, eta=eta)
        _compare_membership_matrices(result.memb, D_ref, atol=1e-4)


# ----- Part 2b: wfcmdd parameter configs -----

class TestWfcmddParameterConfigs:
    """wfcmdd with non-default m / dnoise / alpha vs WeightedCluster."""

    def test_fcmdd_m15_membership_shape(self, seqdata_and_diss):
        """FCMdd m=1.5 produces valid membership."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=1.5)
        _assert_valid_membership(result.memb, NROWS, N_CLUSTERS)

    def test_fcmdd_m15_matches_weightedcluster(self, seqdata_and_diss, ref_dir_wfcmdd):
        """FCMdd m=1.5, k=3 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_wfcmdd, "wfcmdd_fcmdd_k3_m15_memb")
        if D_ref is None:
            pytest.skip("ref_wfcmdd_fcmdd_k3_m15_memb.csv not found")
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=1.5)
        _compare_membership_matrices(result.memb, D_ref, atol=1e-4)

    def test_fcmdd_m30_matches_weightedcluster(self, seqdata_and_diss, ref_dir_wfcmdd):
        """FCMdd m=3.0, k=3 membership matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_wfcmdd, "wfcmdd_fcmdd_k3_m30_memb")
        if D_ref is None:
            pytest.skip("ref_wfcmdd_fcmdd_k3_m30_memb.csv not found")
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="FCMdd", m=3.0)
        _compare_membership_matrices(result.memb, D_ref, atol=1e-4)

    def test_ncdd_dlambda_membership_shape(self, seqdata_and_diss):
        """NCdd with dlambda parameter produces correct shape."""
        _, D = seqdata_and_diss
        seeds = np.array([0, 5, 10])
        result = wfcmdd(D, memb=seeds, method="NCdd", m=2.0, dlambda=2.0)
        assert result.memb.shape == (NROWS, N_CLUSTERS + 1)


# =============================================================================
# Part 3: crispness
# =============================================================================

class TestCrispness:
    """Tests for the crispness utility function."""

    def test_crispness_normalized_range(self, seqdata_and_diss):
        """Normalized crispness is in [0, 1] for all rows."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        crisp = crispness(result.membership, norm=True)
        assert crisp.shape == (NROWS,)
        assert np.all(crisp >= -1e-9), "crispness must be >= 0"
        assert np.all(crisp <= 1.0 + 1e-9), "normalized crispness must be <= 1"

    def test_crispness_hard_assignment_is_one(self):
        """A hard (one-hot) membership row has normalized crispness == 1."""
        memb = np.zeros((3, 3), dtype=float)
        memb[0, 0] = 1.0
        memb[1, 1] = 1.0
        memb[2, 2] = 1.0
        crisp = crispness(memb, norm=True)
        np.testing.assert_allclose(crisp, 1.0, atol=1e-9)

    def test_crispness_uniform_is_zero(self):
        """A uniform membership row has normalized crispness == 0."""
        k = 3
        memb = np.full((5, k), 1.0 / k, dtype=float)
        crisp = crispness(memb, norm=True)
        np.testing.assert_allclose(crisp, 0.0, atol=1e-9)

    def test_crispness_unnormalized(self):
        """Unnormalized crispness equals sum of squared memberships per row."""
        memb = np.array([[0.7, 0.2, 0.1], [0.5, 0.3, 0.2]], dtype=float)
        crisp = crispness(memb, norm=False)
        expected = np.array([
            0.7**2 + 0.2**2 + 0.1**2,
            0.5**2 + 0.3**2 + 0.2**2,
        ])
        np.testing.assert_allclose(crisp, expected, atol=1e-12)

    def test_crispness_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """Normalized crispness for FANNY k=3 matches WeightedCluster reference."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_fanny, "fanny_k3_exp15_crispness")
        if D_ref is None:
            pytest.skip("ref_fanny_k3_exp15_crispness.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        crisp = crispness(result.membership, norm=True)
        ref_vals = D_ref.iloc[:, 0].to_numpy(dtype=np.float64)
        np.testing.assert_allclose(crisp, ref_vals, atol=1e-4, rtol=1e-4)


# =============================================================================
# Part 4: membership_summary
# =============================================================================

class TestMembershipSummary:
    """Tests for membership_summary."""

    def test_membership_summary_returns_dataframe(self, seqdata_and_diss):
        """membership_summary returns a DataFrame."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        assert isinstance(summary, pd.DataFrame)

    def test_membership_summary_shape(self, seqdata_and_diss):
        """membership_summary has 6 rows (Min, 1st Qu., Median, Mean, 3rd Qu., Max) and k columns."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        assert summary.shape == (6, N_CLUSTERS)

    def test_membership_summary_index_labels(self, seqdata_and_diss):
        """membership_summary row labels match R summary() convention."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        expected_labels = ["Min.", "1st Qu.", "Median", "Mean", "3rd Qu.", "Max."]
        assert list(summary.index) == expected_labels

    def test_membership_summary_mean_row_sums_to_one(self, seqdata_and_diss):
        """Mean row of membership_summary sums to 1 (row-stochastic property)."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        mean_sum = summary.loc["Mean"].sum()
        assert np.isclose(mean_sum, 1.0, atol=1e-6), f"Mean row sums to {mean_sum}, expected 1.0"

    def test_membership_summary_min_nonnegative(self, seqdata_and_diss):
        """Min row of membership_summary is non-negative."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        assert (summary.loc["Min."] >= -1e-9).all()

    def test_membership_summary_max_leq_one(self, seqdata_and_diss):
        """Max row is <= 1."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        assert (summary.loc["Max."] <= 1.0 + 1e-9).all()

    def test_membership_summary_as_dict(self, seqdata_and_diss):
        """membership_summary with as_dataframe=False returns dict."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=False)
        assert isinstance(summary, dict)
        assert len(summary) == N_CLUSTERS

    def test_membership_summary_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """membership_summary statistics match WeightedCluster summary() output."""
        _, D = seqdata_and_diss
        D_ref = _load_ref_csv(ref_dir_fanny, "fanny_k3_exp15_memb_summary")
        if D_ref is None:
            pytest.skip("ref_fanny_k3_exp15_memb_summary.csv not found")
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        summary = membership_summary(result.membership, as_dataframe=True)
        ref_vals = D_ref.to_numpy(dtype=np.float64)
        np.testing.assert_allclose(
            summary.to_numpy(), ref_vals, atol=1e-4, rtol=1e-4,
            err_msg="membership_summary differs from WeightedCluster"
        )


# =============================================================================
# Part 5: most_typical_members
# =============================================================================

class TestMostTypicalMembers:
    """Tests for most_typical_members."""

    def test_most_typical_members_returns_dataframe(self, seqdata_and_diss):
        """most_typical_members returns a DataFrame."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=1)
        assert isinstance(df, pd.DataFrame)

    def test_most_typical_members_shape_top1(self, seqdata_and_diss):
        """most_typical_members with top_n=1 returns one row per cluster."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=1)
        assert len(df) == N_CLUSTERS

    def test_most_typical_members_columns(self, seqdata_and_diss):
        """most_typical_members DataFrame has expected columns."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=1)
        for col in ("cluster", "rank", "index", "membership"):
            assert col in df.columns, f"Column '{col}' missing"

    def test_most_typical_members_top3(self, seqdata_and_diss):
        """most_typical_members with top_n=3 returns 3 rows per cluster."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=3)
        assert len(df) == N_CLUSTERS * 3

    def test_most_typical_members_membership_values_decreasing(self, seqdata_and_diss):
        """Within each cluster, membership values are non-increasing (top to bottom)."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=3)
        for cluster_name, group in df.groupby("cluster", sort=False):
            values = group.sort_values("rank")["membership"].to_numpy()
            assert np.all(np.diff(values) <= 1e-12), (
                f"Cluster {cluster_name}: membership not decreasing: {values}"
            )

    def test_most_typical_members_with_labels(self, seqdata_and_diss):
        """most_typical_members with labels returns 'label' column."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        labels = [f"seq_{i}" for i in range(NROWS)]
        df = most_typical_members(result.membership, top_n=1, labels=labels)
        assert "label" in df.columns
        assert df["label"].str.startswith("seq_").all()

    def test_most_typical_members_index_valid(self, seqdata_and_diss):
        """most_typical_members 'index' column contains valid row indices [0, NROWS)."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=1)
        assert (df["index"] >= 0).all()
        assert (df["index"] < NROWS).all()

    def test_most_typical_members_matches_weightedcluster(self, seqdata_and_diss, ref_dir_fanny):
        """most_typical_members index per cluster matches WeightedCluster most.typical reference."""
        _, D = seqdata_and_diss
        ref_path = os.path.join(ref_dir_fanny, "ref_fanny_k3_exp15_most_typical.csv")
        if not os.path.isfile(ref_path):
            pytest.skip("ref_fanny_k3_exp15_most_typical.csv not found")
        D_ref = pd.read_csv(ref_path)
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        df = most_typical_members(result.membership, top_n=1)
        ref_indices = D_ref.iloc[:, 0].to_numpy(dtype=int) - 1  # R is 1-indexed
        seq_indices = df.sort_values("cluster")["index"].to_numpy()
        np.testing.assert_array_equal(
            sorted(seq_indices), sorted(ref_indices),
            err_msg=f"Most typical indices mismatch: Sequenzo={sorted(seq_indices)}, R={sorted(ref_indices)}"
        )


# =============================================================================
# Part 6: Input validation and edge cases
# =============================================================================

class TestInputValidation:
    """Input validation for wfcmdd and get_fuzzy_clusters."""

    def test_wfcmdd_non_square_diss_raises(self):
        """wfcmdd raises ValueError for non-square distance matrix."""
        D = np.array([[0, 1], [1, 0], [0, 1]], dtype=float)
        with pytest.raises(ValueError, match="square"):
            wfcmdd(D, memb=[0, 1], method="FCMdd", m=2.0)

    def test_wfcmdd_negative_diss_raises(self):
        """wfcmdd raises ValueError for negative distances."""
        D = np.array([[0, -1], [-1, 0]], dtype=float)
        with pytest.raises(ValueError, match="non-negative"):
            wfcmdd(D, memb=[0, 1], method="FCMdd", m=2.0)

    def test_wfcmdd_asymmetric_diss_raises(self):
        """wfcmdd raises ValueError for asymmetric distance matrix."""
        D = np.array([[0, 1], [2, 0]], dtype=float)
        with pytest.raises(ValueError, match="symmetric"):
            wfcmdd(D, memb=[0, 1], method="FCMdd", m=2.0)

    def test_wfcmdd_m_leq_1_raises(self):
        """wfcmdd raises ValueError when m <= 1 (for FCMdd)."""
        D = np.array([[0, 1], [1, 0]], dtype=float)
        with pytest.raises(ValueError, match="m must be greater than 1"):
            wfcmdd(D, memb=[0, 1], method="FCMdd", m=1.0)

    def test_wfcmdd_ncdd_no_dnoise_raises(self):
        """NCdd without dnoise or dlambda raises ValueError."""
        D = np.array([[0, 1], [1, 0]], dtype=float)
        with pytest.raises(ValueError):
            wfcmdd(D, memb=[0], method="NCdd", m=2.0)

    def test_wfcmdd_pcmdd_no_eta_raises(self):
        """PCMdd without eta raises ValueError."""
        D = np.array([[0, 1], [1, 0]], dtype=float)
        with pytest.raises(ValueError):
            wfcmdd(D, memb=[0], method="PCMdd", m=2.0)

    def test_get_fuzzy_clusters_invalid_method_raises(self, seqdata_and_diss):
        """get_fuzzy_clusters raises ValueError for unknown method."""
        _, D = seqdata_and_diss
        with pytest.raises(ValueError):
            get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, method="unknown_method")

    def test_crispness_single_cluster_returns_ones(self):
        """crispness for k=1 membership (all 1.0) raises or returns 1.0 (undefined normalization)."""
        memb = np.ones((5, 1), dtype=float)
        # k=1 is degenerate; function should at least not crash
        result = crispness(memb, norm=True)
        assert result.shape == (5,)

    def test_most_typical_members_top_n_zero_raises(self, seqdata_and_diss):
        """most_typical_members raises ValueError for top_n=0."""
        _, D = seqdata_and_diss
        result = get_fuzzy_clusters(D, n_clusters=N_CLUSTERS, memb_exp=1.5, method="fanny")
        with pytest.raises(ValueError):
            most_typical_members(result.membership, top_n=0)

    def test_membership_summary_wrong_ndim_raises(self):
        """membership_summary raises ValueError for 1D input."""
        with pytest.raises(ValueError):
            membership_summary(np.array([0.3, 0.3, 0.4]), as_dataframe=True)
