"""
@Author  : Yuqi Liang 梁彧祺
@File    : test_traminer_consistency.py
@Time    : 2026-02-11 9:26
@Desc    : Numerical consistency tests comparing Sequenzo with TraMineR reference results.

**Purpose: Numerical Consistency Verification**
This test module performs precise numerical comparisons between Sequenzo's compare_differences
functions and TraMineR/TraMineRextras reference results. These tests ensure that Sequenzo
produces identical (within floating-point tolerance) results to TraMineR.

**Key Characteristics:**
- Requires TraMineR reference files: Needs CSV files generated by `traminer_reference.R`
- Strict numerical tolerance: Uses RTOL=1e-6, ATOL=1e-8 for comparisons
- Skips gracefully: If reference files are missing, tests are skipped (not failed)
- Comprehensive coverage: Tests all key numerical outputs with different parameter combinations

**What is tested:**
- `compare_groups_across_positions()` vs TraMineR's `seqdiff()`: Statistics and discrepancy values
- `compare_groups_overall()` vs TraMineRextras's `seqCompare()`: LRT and BIC statistics
- `compute_likelihood_ratio_test()` vs TraMineRextras's `seqLRT()`: LRT statistics
- `compute_bayesian_information_criterion_test()` vs TraMineRextras's `seqBIC()`: BIC statistics

**Prerequisites:**
Before running these tests, generate TraMineR reference files:
```bash
Rscript tests/compare_differences/traminer_reference.R
```

**When to use:**
- Before releases: Verify that implementation matches TraMineR exactly
- After code changes: Ensure modifications don't break numerical consistency
- For debugging: Identify discrepancies when results don't match TraMineR
- For validation: Confirm that formulas and algorithms are correctly implemented

**For functional testing without TraMineR, see:**
- `test_compare_differences_lsog.py`: Functional tests that don't require reference files
"""

import pytest
import pandas as pd
import numpy as np
import os
from sequenzo import SequenceData
from sequenzo.datasets import load_dataset
from sequenzo.compare_differences import (
    compare_groups_across_positions,
    compare_groups_overall,
    compute_likelihood_ratio_test,
    compute_bayesian_information_criterion_test,
)


# Tolerance for numerical comparisons
RTOL = 1e-6  # Relative tolerance
ATOL = 1e-8  # Absolute tolerance


# Test dataset setup
@pytest.fixture
def lsog_seqdata():
    """Load and prepare dyadic_children dataset (lsog) for testing."""
    df = load_dataset("dyadic_children")
    time_list = [c for c in df.columns if str(c).isdigit()]
    time_list = sorted(time_list, key=int)
    df = df.head(20)
    states = [1, 2, 3, 4, 5, 6]
    seqdata = SequenceData(df, time=time_list, id_col="dyadID", states=states)
    return seqdata


@pytest.fixture
def lsog_group():
    """Create grouping variable for lsog data (two groups of 10 each)."""
    return np.array(['A'] * 10 + ['B'] * 10)


def _load_reference_file(filename):
    """Load reference file if it exists."""
    ref_path = os.path.join(
        os.path.dirname(__file__),
        filename
    )
    if os.path.exists(ref_path):
        return pd.read_csv(ref_path)
    return None


# ============================================================================
# Test compare_groups_across_positions vs TraMineR seqdiff
# ============================================================================

def test_seqdiff_cmprange01_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_across_positions with TraMineR seqdiff (cmprange=(0,1))."""
    ref_stat = _load_reference_file("ref_seqdiff_stat_cmprange01.csv")
    ref_disc = _load_reference_file("ref_seqdiff_discrepancy_cmprange01.csv")
    
    if ref_stat is None or ref_disc is None:
        pytest.skip("Reference files not found. Run traminer_reference.R first.")
    
    # Run Sequenzo function
    result = compare_groups_across_positions(
        lsog_seqdata,
        group=lsog_group,
        cmprange=(0, 1),
        seqdist_args={'method': 'LCS', 'norm': 'auto'},
        with_missing=False,
        weighted=True,
        squared=False
    )
    
    # Compare statistics
    stat_cols = ['Pseudo F', 'Pseudo Fbf', 'Pseudo R2', 'Bartlett', 'Levene']
    for col in stat_cols:
        if col in ref_stat.columns and col in result['stat'].columns:
            sequenzo_vals = result['stat'][col].values
            traminer_vals = ref_stat[col].values
            
            # Handle NaN values
            mask = ~(np.isnan(sequenzo_vals) | np.isnan(traminer_vals))
            if np.any(mask):
                assert np.allclose(
                    sequenzo_vals[mask], traminer_vals[mask],
                    rtol=RTOL, atol=ATOL
                ), f"{col} mismatch"
    
    # Compare discrepancy
    sequenzo_disc = result['discrepancy'].values
    traminer_disc = ref_disc.values
    
    assert np.allclose(sequenzo_disc, traminer_disc, rtol=RTOL, atol=ATOL), \
        "Discrepancy mismatch"
    
    print("[✓] seqdiff with cmprange=(0,1) matches TraMineR")


def test_seqdiff_cmprange_neg22_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_across_positions with TraMineR seqdiff (cmprange=(-2,2))."""
    ref_stat = _load_reference_file("ref_seqdiff_stat_cmprange-22.csv")
    ref_disc = _load_reference_file("ref_seqdiff_discrepancy_cmprange-22.csv")
    
    if ref_stat is None or ref_disc is None:
        pytest.skip("Reference files not found. Run traminer_reference.R first.")
    
    result = compare_groups_across_positions(
        lsog_seqdata,
        group=lsog_group,
        cmprange=(-2, 2),
        seqdist_args={'method': 'LCS', 'norm': 'auto'},
        with_missing=False,
        weighted=True,
        squared=False
    )
    
    # Compare statistics
    stat_cols = ['Pseudo F', 'Pseudo Fbf', 'Pseudo R2', 'Bartlett', 'Levene']
    for col in stat_cols:
        if col in ref_stat.columns and col in result['stat'].columns:
            sequenzo_vals = result['stat'][col].values
            traminer_vals = ref_stat[col].values
            
            mask = ~(np.isnan(sequenzo_vals) | np.isnan(traminer_vals))
            if np.any(mask):
                assert np.allclose(
                    sequenzo_vals[mask], traminer_vals[mask],
                    rtol=RTOL, atol=ATOL
                ), f"{col} mismatch"
    
    print("[✓] seqdiff with cmprange=(-2,2) matches TraMineR")


def test_seqdiff_OM_method_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_across_positions with TraMineR seqdiff (method='OM')."""
    ref_stat = _load_reference_file("ref_seqdiff_stat_OM.csv")
    
    if ref_stat is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_across_positions(
        lsog_seqdata,
        group=lsog_group,
        cmprange=(0, 1),
        seqdist_args={'method': 'OM', 'norm': 'auto', 'sm': 'TRATE'},
        with_missing=False,
        weighted=True,
        squared=False
    )
    
    # Compare Pseudo R2 (main statistic)
    if 'Pseudo R2' in ref_stat.columns and 'Pseudo R2' in result['stat'].columns:
        sequenzo_vals = result['stat']['Pseudo R2'].values
        traminer_vals = ref_stat['Pseudo R2'].values
        
        mask = ~(np.isnan(sequenzo_vals) | np.isnan(traminer_vals))
        if np.any(mask):
            assert np.allclose(
                sequenzo_vals[mask], traminer_vals[mask],
                rtol=RTOL, atol=ATOL
            ), "Pseudo R2 mismatch"
    
    print("[✓] seqdiff with method='OM' matches TraMineR")


def test_seqdiff_squared_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_across_positions with TraMineR seqdiff (squared=TRUE)."""
    ref_stat = _load_reference_file("ref_seqdiff_stat_squared.csv")
    
    if ref_stat is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_across_positions(
        lsog_seqdata,
        group=lsog_group,
        cmprange=(0, 1),
        seqdist_args={'method': 'LCS', 'norm': 'auto'},
        with_missing=False,
        weighted=True,
        squared=True
    )
    
    # Compare Pseudo R2
    if 'Pseudo R2' in ref_stat.columns and 'Pseudo R2' in result['stat'].columns:
        sequenzo_vals = result['stat']['Pseudo R2'].values
        traminer_vals = ref_stat['Pseudo R2'].values
        
        mask = ~(np.isnan(sequenzo_vals) | np.isnan(traminer_vals))
        if np.any(mask):
            assert np.allclose(
                sequenzo_vals[mask], traminer_vals[mask],
                rtol=RTOL, atol=ATOL
            ), "Pseudo R2 mismatch (squared)"
    
    print("[✓] seqdiff with squared=TRUE matches TraMineR")


# ============================================================================
# Test compare_groups_overall vs TraMineRextras seqCompare
# ============================================================================

def test_seqCompare_LCS_all_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (stat='all')."""
    ref = _load_reference_file("ref_seqCompare_LCS_all.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    # Run Sequenzo function
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        stat="all",
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare all columns by index (result is numpy array)
    # Expected order: LRT, p-value, Delta BIC, Bayes Factor
    assert result.shape[1] >= len(ref.columns), "Result has fewer columns than reference"
    
    for i, col in enumerate(ref.columns):
        sequenzo_val = result[0, i]
        traminer_val = ref[col].values[0]
        
        assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
            f"{col} mismatch: Sequenzo={sequenzo_val:.10f}, TraMineR={traminer_val:.10f}"
    
    print("[✓] seqCompare with stat='all' matches TraMineRextras")


def test_seqCompare_LCS_LRT_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (stat='LRT')."""
    ref = _load_reference_file("ref_seqCompare_LCS_LRT.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        stat="LRT",
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare LRT and p-value by index
    # Expected order: LRT, p-value
    for i, col in enumerate(ref.columns):
        sequenzo_val = result[0, i]
        traminer_val = ref[col].values[0]
        
        assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
            f"{col} mismatch"
    
    print("[✓] seqCompare with stat='LRT' matches TraMineRextras")


def test_seqCompare_LCS_BIC_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (stat='BIC')."""
    ref = _load_reference_file("ref_seqCompare_LCS_BIC.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        stat="BIC",
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare Delta BIC and Bayes Factor by index
    # Expected order: Delta BIC, Bayes Factor
    for i, col in enumerate(ref.columns):
        sequenzo_val = result[0, i]
        traminer_val = ref[col].values[0]
        
        assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
            f"{col} mismatch"
    
    print("[✓] seqCompare with stat='BIC' matches TraMineRextras")


def test_seqCompare_OM_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (method='OM')."""
    ref = _load_reference_file("ref_seqCompare_OM_all.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        stat="all",
        squared="LRTonly",
        weighted=True,
        method="OM",
        sm="TRATE"
    )
    
    # Compare LRT (first column, index 0)
    lrt_col_idx = list(ref.columns).index('LRT') if 'LRT' in ref.columns else 0
    sequenzo_val = result[0, lrt_col_idx]
    traminer_val = ref['LRT'].values[0]
    
    assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
        f"LRT mismatch: Sequenzo={sequenzo_val:.10f}, TraMineR={traminer_val:.10f}"
    
    print("[✓] seqCompare with method='OM' matches TraMineRextras")


def test_seqCompare_s0_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (s=0, no sampling)."""
    ref = _load_reference_file("ref_seqCompare_s0.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=0,
        seed=36963,
        stat="all",
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare LRT (first column, index 0)
    lrt_col_idx = list(ref.columns).index('LRT') if 'LRT' in ref.columns else 0
    sequenzo_val = result[0, lrt_col_idx]
    traminer_val = ref['LRT'].values[0]
    
    assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
        "LRT mismatch (s=0)"
    
    print("[✓] seqCompare with s=0 matches TraMineRextras")


def test_seqCompare_s50_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (s=50)."""
    ref = _load_reference_file("ref_seqCompare_s50.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=50,
        seed=36963,
        stat="all",
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare LRT (first column, index 0)
    lrt_col_idx = list(ref.columns).index('LRT') if 'LRT' in ref.columns else 0
    sequenzo_val = result[0, lrt_col_idx]
    traminer_val = ref['LRT'].values[0]
    
    assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
        "LRT mismatch (s=50)"
    
    print("[✓] seqCompare with s=50 matches TraMineRextras")


def test_seqCompare_unweighted_consistency(lsog_seqdata, lsog_group):
    """Compare compare_groups_overall with TraMineRextras seqCompare (weighted=FALSE)."""
    ref = _load_reference_file("ref_seqCompare_unweighted.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compare_groups_overall(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        stat="all",
        squared="LRTonly",
        weighted=False,
        method="LCS"
    )
    
    # Compare LRT (first column, index 0)
    lrt_col_idx = list(ref.columns).index('LRT') if 'LRT' in ref.columns else 0
    sequenzo_val = result[0, lrt_col_idx]
    traminer_val = ref['LRT'].values[0]
    
    assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
        "LRT mismatch (unweighted)"
    
    print("[✓] seqCompare with weighted=FALSE matches TraMineRextras")


# ============================================================================
# Test compute_likelihood_ratio_test vs TraMineRextras seqLRT
# ============================================================================

def test_seqLRT_consistency(lsog_seqdata, lsog_group):
    """Compare compute_likelihood_ratio_test with TraMineRextras seqLRT."""
    ref = _load_reference_file("ref_seqLRT_LCS.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compute_likelihood_ratio_test(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare LRT and p-value by index
    # Expected order: LRT, p-value
    for i, col in enumerate(ref.columns):
        sequenzo_val = result[0, i]
        traminer_val = ref[col].values[0]
        
        assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
            f"{col} mismatch"
    
    print("[✓] seqLRT matches TraMineRextras")


# ============================================================================
# Test compute_bayesian_information_criterion_test vs TraMineRextras seqBIC
# ============================================================================

def test_seqBIC_consistency(lsog_seqdata, lsog_group):
    """Compare compute_bayesian_information_criterion_test with TraMineRextras seqBIC."""
    ref = _load_reference_file("ref_seqBIC_LCS.csv")
    
    if ref is None:
        pytest.skip("Reference file not found. Run traminer_reference.R first.")
    
    result = compute_bayesian_information_criterion_test(
        lsog_seqdata,
        group=lsog_group,
        s=100,
        seed=36963,
        squared="LRTonly",
        weighted=True,
        method="LCS"
    )
    
    # Compare Delta BIC and Bayes Factor by index
    # Expected order: Delta BIC, Bayes Factor
    for i, col in enumerate(ref.columns):
        sequenzo_val = result[0, i]
        traminer_val = ref[col].values[0]
        
        assert np.isclose(sequenzo_val, traminer_val, rtol=RTOL, atol=ATOL), \
            f"{col} mismatch"
    
    print("[✓] seqBIC matches TraMineRextras")
