name: Run Tests for Sequenzo Pull Requests

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    name: Tests on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout target branch code (safe)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Fetch PR branch changes
        run: git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout PR changes
        run: git checkout -qf FETCH_HEAD

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary numpy scipy
          pip install --prefer-binary Cython pybind11 pytest

      - name: Build C++ extension first
        run: |
          python sequenzo/clustering/setup_pam.py build_ext --inplace
          python sequenzo/clustering/setup_kmedoids.py build_ext --inplace

      - name: Run Tests
        run: pytest tests --verbose
